### ISSUE TITLE
Session timed out over night

### ISSUE THREAD

**Issue by BartBruininks** [marrink-lab/VisualizationServer#1]
I was trying to stress test the server and test its performance over night, however, when I tried to log into it in the morning I got the message that my session timed out. It would be nice if there would be an option to prevent this from happening if the users explicitly specifies that he/she would want the instance to remain active. In the future this could be account/user dependent. A maximum could be the allowed hours which the machine was booked.

**Comment by zilverberg** [comment]
The maximum reservation time has been increased to 24 hours.
