### ISSUE TITLE
Failed to initiated service

### ISSUE THREAD

**Issue by BartBruininks** [marrink-lab/VisualizationServer#11]
In the log it appears as if there is a licensing issue.

**Comment by zilverberg** [comment]
This is probably one me.
I accidently removed files from the license server and apperently readding them didnt work.
Can you try again?

**Comment by BartBruininks** [comment]
Nothing changed on my side, its still failing in the same manner (it seems).

**Comment by zilverberg** [comment]
I broke the licensing server.
Will rebuild between meetings.

**Comment by zilverberg** [comment]
Fixed.
