### ISSUE TITLE
EnginFrame License Error

### ISSUE THREAD

**Issue by jan-stevens** [marrink-lab/VisualizationServer#13]
Hi,

There seems to be a license error which prevents users from starting up a session.
When I log in and try to create a session, the following error is thrown:

**EnginFrame License Error**
```
No available tokens for license id (EF Base@NICE) - Total tokens (1) - license id (EF Base@NICE) - license file (/opt/nice/enginframe/license/license.ef)
Please request a new license for this host address(es): [(129.125.60.53, nice.hpc.rug.nl)]
```

**Comment by jan-stevens** [comment]
This error seems to have fixed itself.

**Comment by zilverberg** [comment]
We currently only have one license for the environment, so if someone else is using it you get this error.
