### ISSUE TITLE
Failed interactive job submission

### ISSUE THREAD

**Issue by jan-stevens** [marrink-lab/VisualizationServer#14]
Hi,

When trying to start an interactive session the following error is thrown:
```
Failed interactive job submission: SLURM plugin: Could not start the requested session, sbatch failed
```
Does this error occur when another user is already connected to the server? Looking at the server status however, it seems to be idling.

Apologies for the spam!

**Comment by zilverberg** [comment]
Hi Jan-stevens,

Could you send an email with this problem to hpc@rug.nl?
We can see private information (like your pnumber) there which we dont want on github.
The server is idling, so if you are a member of the reservation it should work, I'm thinking you arent included in the reservation.

Gr,
Henk-Jan

**Comment by jan-stevens** [comment]
Thanks for the info, I will contact CIT via email.

Gr. Jan
