### ISSUE TITLE
Cannot create new instance after connection timed out

### ISSUE THREAD

**Issue by BartBruininks** [marrink-lab/VisualizationServer#2]
I was trying to run stress test over night, but when I came back in the morning my connection to the server timed out and my sessions seems to have been closed. However, when I try to create a new session the server keeps pending in the NICE services lab01 screen. I seem to be unable to start a new session.

**Comment by zilverberg** [comment]
There is a hardware problem which causes slurm to flag the node as faulty and stops new jobs from getting started. Not a bug but a feature. We are looking into the hardware problem.

**Comment by BartBruininks** [comment]
Hardware was broken and we are waiting for the new drives to arrive from Dell. We do not assume that this will be a returning issue since it is due to initial hardware failure. Whenever the server is online again we will remove the status 'offline' from the readme.

**Comment by BartBruininks** [comment]
The hardware problem was resolved.
