### ISSUE TITLE
GPUs linked by SLI instead of NVLINK

### ISSUE THREAD

**Issue by BartBruininks** [marrink-lab/VisualizationServer#3]
it is declared in the specifications that the GPUs are linked through SLI. This does not allow for full shared memory between the GPUs and will result in a maximum of 48 GB of VRAM where a maximum of 76 GB is possible if the GPUs are properly set up using NVLINK

**Comment by zilverberg** [comment]
This is faulty stated in the specifications. There is indeed a NVLINK used.

[root@pg-lab01 ~]# nvidia-smi topo --matrix
        GPU0    GPU1    CPU Affinity
GPU0     X      NV2     0-39
GPU1    NV2      X      0-39

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks
