### ISSUE TITLE
The local drives (nvme and spinning) are both not reachable (permission denied)

### ISSUE THREAD

**Issue by BartBruininks** [marrink-lab/VisualizationServer#4]
I tried to make a folder on the local drives for testing but I could not. I have been given a personal folder on NVMe, but I do not have one for the basic spinning local. Nevertheless this needs to be fixed for other users as well. For now this stops me from comparing the NVMe to the local spinning drives.

**Comment by zilverberg** [comment]
I changed the rights on /local and /nvme to 777, allowing everyone to create files and directories.
As these are local storage solutions, they should be cleared after use!
Automation for this needs to be scripted yet.
